on:
  push:
    branches:
      - main
#  pull_request:
  #   branches:
 #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: python -m unittest test_ci_message.py
